spring:
  datasource:
    url: jdbc:mysql://mysql:3306/moimg?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: moloom
    password: mo
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis           # Redis服务器地址
      database: 0               # Redis数据库索引（默认为0）
      port: 6379              # Redis服务器连接端口
      #    username: mo
      password: mo             # Redis服务器连接密码（默认为空）
      timeout: 1000ms         # 连接超时时间
      lettuce: #配置连接池
        pool:
          max-active: 30       #连接池最大连接数
          max-idle: 10         #连接池最大空闲数
          min-idle: 4         #连接词最小空闲连接数
          max-wait: -1ms      #连接池最大阻塞等待实践，负值表示没有限制
moimg:
  host: "https://img.moloom.cn"    # 当前系统的域名，生成图片连接时会用到

minio:
  server:
    host: "http://minio:9000"
    access-key: "az5UMt1YqCueE8StuUtQ"
    secret-key: "AMip5jaSAeHKhwlmjcpS8NKfTTNfdCHl9x8EpLeb"



