spring:
  datasource:
    url: jdbc:mysql://moloom.cn:8806/moimg?autoReconnect=true&socketTimeout=10000&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: moloom
    password: mo
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 360000  # 连接最大存活时间,单位为毫秒
      idle-timeout: 300000  # 连接最大空闲时间,单位为毫秒
      validation-timeout: 50000  # 连接检查时间间隔,单位为毫秒
      connection-test-query: SELECT 1   # 连接检查语句
      minimum-idle: 10     # 最小空闲连接数
      maximum-pool-size: 20     # 最大连接数
  data:
    redis:
      host: moloom.cn
      database: 0               # Redis数据库索引（默认为0）
      port: 8809              # Redis服务器连接端口
      #    username: mo
      password: mo             # Redis服务器连接密码（默认为空）
      timeout: 5000ms         # 连接超时时间
      lettuce: #配置连接池
        pool:
          max-active: 30       #连接池最大连接数
          max-idle: 10         #连接池最大空闲数
          min-idle: 5         #连接词最小空闲连接数
          max-wait: 3200ms      #连接池最大阻塞等待实践，负值表示没有限制
          time-between-eviction-runs: 60000   #运行时检查空闲连接间隔,单位为毫秒
        shutdown-timeout: 300ms   #关闭连接池等待时间
moimg:
  host: "http://localhost:${server.port}"    # 当前系统的域名，生成图片连接时会用到

minio:
  server:
    host: "http://moloom.cn:8807"
    access-key: "az5UMt1YqCueE8StuUtQ"
    secret-key: "AMip5jaSAeHKhwlmjcpS8NKfTTNfdCHl9x8EpLeb"



