server:
  port: 8803
  tomcat:
    threads:
      max: 50  # 最大线程数
      min-spare: 20   # 最小线程数

spring:
  application:
    name: "api"
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1GB
      file-size-threshold: 2MB    # 文件大于此值会才存入临时文件，小于直接存入内存

mybatis:
  configuration:
    map-underscore-to-camel-case: true    # 开启驼峰命名转换
  mapper-locations: classpath:mapper/*.xml

# 设置sql语句的日志级别
logging:
  level:
    org:
      springframework:
        jdbc: debug
        sql: debug
    com:
      zaxxer:
        hikari: info
# moImg args
moimg:
  upload:
    upload-root-path: "/api/files"
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

minio:
  buckets: #桶名称，第一个是存图片的，第二个是存视频的
    - bucket-name: "images"
      bucket-tags:
        type: "image"
        author: "moloom"
    - bucket-name: "videos"
      bucket-tags:
        type: "video"
        author: "moloom"
